# Generated by Django 4.0.6 on 2022-08-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='farms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_days', to='listings.listing'),
        ),
    ]
